import { CSS } from './style.js';
import { LOGO_DATA_URI } from './logo.js';
import { getVersion } from '../version.js';
import { getConfig } from '../config.js';

const NAV = [
  { section: 'MAIN' },
  { href: '/', label: 'Home', icon: '' },
  { href: '/tunnel', label: 'Tunnel', icon: '' },
  { href: '/providers', label: 'Providers', icon: '' },
  { href: '/combos', label: 'Combos', icon: '' },
  { section: 'SYSTEM' },
  { href: '/keys', label: 'API Keys', icon: '' },
  { href: '/cli', label: 'CLI Tools', icon: '' },
  { href: '/usage', label: 'Usage', icon: '' },
  { href: '/logs', label: 'Console Log', icon: '' },
  { href: '/settings', label: 'Settings', icon: '' }
];

export function layout(title, body, { active = '/', refresh = 0 } = {}) {
  const metaRefresh = refresh > 0
    ? '<meta http-equiv="refresh" content="' + refresh + '">' : '';

  let authKey = '';
  try {
    const cfg = getConfig();
    authKey = (cfg.clients && cfg.clients[0] && cfg.clients[0].key) || '';
  } catch (e) {}

  const ver = getVersion();

  const nav = NAV.map(item => {
    if (item.section) return '<div class="section-label">' + item.section + '</div>';
    const cls = 'nav-item' + (item.href === active ? ' active' : '');
    return '<a href="' + item.href + '" class="' + cls + '">' +
      '<span class="nav-icon">' + item.icon + '</span>' +
      '<span>' + item.label + '</span>' +
    '</a>';
  }).join('');

  const head = [
    '<!DOCTYPE html>',
    '<html lang="en" data-theme="light">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=5">',
    '<meta name="color-scheme" content="dark light">',
    '<title>' + title + '  Loka</title>',
    metaRefresh,
    '<link rel="icon" type="image/png" href="/icons/loka-logo.png">',
    '<script>(function(){try{var t=localStorage.getItem("loka-theme")||"light";document.documentElement.setAttribute("data-theme",t)}catch(e){}})();<\/script>',
    '<style>' + CSS + '</style>',
    '</head>'
  ].join('\n');

  const bodyHtml = [
    '<body>',
    '<div class="blob-3"></div>',
    '<div class="sidebar-overlay" id="sidebarOverlay"></div>',
    '<button class="menu-toggle" onclick="toggleSidebar()" aria-label="Menu"></button>',
    '<aside id="sidebar">',
    '  <div class="brand">',
    '    <img src="' + LOGO_DATA_URI + '" alt="Loka" class="brand-logo">',
    '    <div class="version-pill" title="' + ver.display + '">' + ver.short + '</div>',
    '    <a href="/cli" class="update-badge" id="updateBadge" style="display:none"> Update tersedia</a>',
    '  </div>',
    '  <nav>' + nav + '</nav>',
    '  <div class="sidebar-foot">',
    '    <button class="icon-btn" onclick="toggleTheme()" title="Toggle theme"><span id="themeIcon"></span></button>',
    '  </div>',
    '</aside>',
    '<main>',
    '  <header class="page-header"><h1>' + title + '</h1></header>',
    body,
    '</main>',
    '<div class="loka-dialog-overlay" id="lokaDialog" style="display:none">',
    '  <div class="loka-dialog">',
    '    <div class="loka-dialog-icon" id="lokaDialogIcon">?</div>',
    '    <h3 id="lokaDialogTitle"></h3>',
    '    <p id="lokaDialogMessage"></p>',
    '    <div id="lokaDialogInputWrap" style="display:none;margin-bottom:1.35rem"></div>',
    '    <div class="loka-dialog-actions">',
    '      <button class="ghost" id="lokaDialogCancel">Cancel</button>',
    '      <button id="lokaDialogConfirm">OK</button>',
    '    </div>',
    '  </div>',
    '</div>',
    '<div class="toast" id="toast"></div>'
  ].join('\n');

  const scriptJS = [
    '<script>',
    'var LOKA_KEY = ' + JSON.stringify(authKey) + ';',
    'window.LOKA_KEY = LOKA_KEY;',
    '',
    'window.toast = function(m, o) {',
    '  var t = document.getElementById("toast");',
    '  var d = (o && o.duration) || 2500;',
    '  t.textContent = m;',
    '  t.classList.add("show");',
    '  clearTimeout(t._t);',
    '  t._t = setTimeout(function(){ t.classList.remove("show"); }, d);',
    '};',
    '',
    'function isMobile() { return window.matchMedia("(max-width:900px)").matches; }',
    '',
    'function toggleSidebar() {',
    '  var willHide = !document.body.classList.contains("sidebar-hidden");',
    '  var ov = document.getElementById("sidebarOverlay");',
    '  if (willHide) {',
    '    document.body.classList.add("sidebar-hidden");',
    '    if (ov) ov.classList.remove("show");',
    '    try { localStorage.setItem("loka-sidebar", "hidden"); } catch(e) {}',
    '  } else {',
    '    document.body.classList.remove("sidebar-hidden");',
    '    if (ov && isMobile()) ov.classList.add("show");',
    '    try { localStorage.setItem("loka-sidebar", "shown"); } catch(e) {}',
    '  }',
    '}',
    '',
    'function closeSidebar() {',
    '  if (document.body.classList.contains("sidebar-hidden")) return;',
    '  document.body.classList.add("sidebar-hidden");',
    '  var ov = document.getElementById("sidebarOverlay");',
    '  if (ov) ov.classList.remove("show");',
    '  try { localStorage.setItem("loka-sidebar", "hidden"); } catch(e) {}',
    '}',
    '',
    'function toggleTheme() {',
    '  var cur = document.documentElement.getAttribute("data-theme");',
    '  var next = cur === "dark" ? "light" : "dark";',
    '  document.documentElement.setAttribute("data-theme", next);',
    '  try { localStorage.setItem("loka-theme", next); } catch(e) {}',
    '  syncThemeIcon();',
    '}',
    '',
    'function syncThemeIcon() {',
    '  var t = document.documentElement.getAttribute("data-theme");',
    '  var i = document.getElementById("themeIcon");',
    '  if (i) i.textContent = t === "dark" ? "" : "";',
    '}',
    'syncThemeIcon();',
    '',
    '// Restore sidebar state',
    '(function() {',
    '  try {',
    '    var s = localStorage.getItem("loka-sidebar");',
    '    var m = isMobile();',
    '    if (s === "hidden" || (s === null && m)) {',
    '      document.body.classList.add("sidebar-hidden");',
    '    } else if (m) {',
    '      var ov = document.getElementById("sidebarOverlay");',
    '      if (ov) ov.classList.add("show");',
    '    }',
    '  } catch(e) {}',
    '})();',
    '',
    '// Overlay click closes sidebar',
    'document.getElementById("sidebarOverlay").addEventListener("click", closeSidebar);',
    '',
    '// Nav link click closes sidebar on mobile',
    'document.querySelectorAll("aside nav a").forEach(function(a) {',
    '  a.addEventListener("click", function() {',
    '    if (isMobile()) closeSidebar();',
    '  });',
    '});',
    '',
    '// Escape key closes sidebar',
    'document.addEventListener("keydown", function(e) {',
    '  if (e.key === "Escape" && isMobile()) closeSidebar();',
    '});',
    '',
    '// Dialog system',
    'window.dialog = {',
    '  confirm: function(m, o) {',
    '    return window._showDialog({',
    '      title: (o && o.title) || "Konfirmasi",',
    '      message: m,',
    '      confirmText: (o && o.confirmText) || "OK",',
    '      cancelText: (o && o.cancelText) || "Batal",',
    '      icon: (o && o.icon) || "?"',
    '    });',
    '  },',
    '  alert: function(m, o) {',
    '    return window._showDialog({',
    '      title: (o && o.title) || "Info",',
    '      message: m,',
    '      confirmText: (o && o.confirmText) || "OK",',
    '      cancelText: null,',
    '      icon: (o && o.icon) || "i"',
    '    });',
    '  },',
    '  prompt: function(m, d, o) {',
    '    return window._showDialog({',
    '      title: (o && o.title) || "Input",',
    '      message: m,',
    '      input: true,',
    '      value: (d === undefined || d === null) ? "" : String(d),',
    '      confirmText: (o && o.confirmText) || "OK",',
    '      cancelText: (o && o.cancelText) || "Batal",',
    '      icon: (o && o.icon) || ""',
    '    });',
    '  }',
    '};',
    '',
    'window._showDialog = function(opts) {',
    '  return new Promise(function(resolve) {',
    '    var ov = document.getElementById("lokaDialog");',
    '    var ic = document.getElementById("lokaDialogIcon");',
    '    var ti = document.getElementById("lokaDialogTitle");',
    '    var me = document.getElementById("lokaDialogMessage");',
    '    var wrap = document.getElementById("lokaDialogInputWrap");',
    '    var bc = document.getElementById("lokaDialogCancel");',
    '    var bk = document.getElementById("lokaDialogConfirm");',
    '',
    '    ic.textContent = opts.icon || "?";',
    '    ti.textContent = opts.title || "";',
    '    me.textContent = opts.message || "";',
    '    bk.textContent = opts.confirmText || "OK";',
    '    bc.textContent = opts.cancelText || "Batal";',
    '    bc.style.display = opts.cancelText ? "" : "none";',
    '',
    '    wrap.innerHTML = "";',
    '    var input = null;',
    '    if (opts.input) {',
    '      wrap.style.display = "";',
    '      input = document.createElement("input");',
    '      input.type = "text";',
    '      input.autocomplete = "off";',
    '      input.autocorrect = "off";',
    '      input.autocapitalize = "off";',
    '      input.spellcheck = false;',
    '      input.name = "loka_dlg_" + Date.now() + "_" + Math.random().toString(36).slice(2);',
    '      input.value = opts.value || "";',
    '      wrap.appendChild(input);',
    '    } else {',
    '      wrap.style.display = "none";',
    '    }',
    '',
    '    ov.style.display = "flex";',
    '    if (input) setTimeout(function(){ input.focus(); input.select(); }, 60);',
    '',
    '    function done(v) {',
    '      ov.style.display = "none";',
    '      bk.removeEventListener("click", onOk);',
    '      bc.removeEventListener("click", onCancel);',
    '      ov.removeEventListener("click", onOverlay);',
    '      document.removeEventListener("keydown", onKey);',
    '      wrap.innerHTML = "";',
    '      resolve(v);',
    '    }',
    '    function onOk() { done(input ? input.value : true); }',
    '    function onCancel() { done(input ? null : false); }',
    '    function onOverlay(e) { if (e.target === ov) done(input ? null : false); }',
    '    function onKey(e) {',
    '      if (e.key === "Escape") done(input ? null : false);',
    '      else if (e.key === "Enter" && input) done(input.value);',
    '    }',
    '',
    '    bk.addEventListener("click", onOk);',
    '    bc.addEventListener("click", onCancel);',
    '    ov.addEventListener("click", onOverlay);',
    '    document.addEventListener("keydown", onKey);',
    '  });',
    '};',
    '',
    '// Tunnel notification poll',
    '(function() {',
    '  if (!LOKA_KEY) return;',
    '  var notified = {};',
    '  function poll() {',
    '    fetch("/api/tunnel/notifications", { headers: { "Authorization": "Bearer " + LOKA_KEY } })',
    '      .then(function(r){ return r.ok ? r.json() : null; })',
    '      .then(function(d) {',
    '        if (!d || !d.notifications || !d.notifications.length) return;',
    '        var fresh = d.notifications.filter(function(n){ return !notified[n.id]; });',
    '        if (!fresh.length) return;',
    '        fresh.forEach(function(n) {',
    '          notified[n.id] = true;',
    '          window.toast(n.message, { duration: 12000 });',
    '        });',
    '        fetch("/api/tunnel/mark-read", { method: "POST", headers: { "Authorization": "Bearer " + LOKA_KEY } }).catch(function(){});',
    '      })',
    '      .catch(function(){});',
    '  }',
    '  setTimeout(poll, 1500);',
    '  setInterval(poll, 20000);',
    '})();',
    '',
    '// Update check poll',
    '(function() {',
    '  if (!LOKA_KEY) return;',
    '  var shown = false;',
    '  function poll() {',
    '    fetch("/api/update/state", { headers: { "Authorization": "Bearer " + LOKA_KEY } })',
    '      .then(function(r){ return r.ok ? r.json() : null; })',
    '      .then(function(d) {',
    '        if (!d || !d.updateAvailable) return;',
    '        var badge = document.getElementById("updateBadge");',
    '        if (badge) {',
    '          badge.style.display = "flex";',
    '          badge.title = "Update: " + d.installed + " -> " + d.latest;',
    '        }',
    '        if (!shown) {',
    '          shown = true;',
    '          window.toast("Update tersedia: " + d.latest, { duration: 10000 });',
    '        }',
    '      })',
    '      .catch(function(){});',
    '  }',
    '  setTimeout(poll, 3000);',
    '  setInterval(poll, 60000);',
    '})();',
    '<\/script>'
  ].join('\n');

  return head + '\n' + bodyHtml + '\n' + scriptJS + '\n</body>\n</html>';
}